//User Reducer
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USER_PREFERENCES_SUCCESS = "USER_PREFERENCES_SUCCESS";
export const USER_PREFERENCES_FAIL = "USER_PREFERENCES_FAIL";
export const USER_LOADED = "USER_LOADED";
export const LOGOUT = "LOGOUT";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const AUTH_ERROR = "AUTH_ERROR";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

//Alert Reducer
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

//Game Reducer

//Schedule games related
export const SCHEDULE_SUCCESS = "SCHEDULE_SUCCESS";
export const SCHEDULE_FAIL = "SCHEDULE_FAIL";
export const LOAD_GAMES_SUCCESS = "LOAD_GAMES_SUCCESS";
export const LOAD_GAMES_FAIL = "LOAD_GAMES_FAIL";
export const LOAD_MY_GAMES_SUCCESS = "LOAD_MY_GAMES_SUCCESS";
export const LOAD_MY_GAMES_FAIL = "LOAD_MY_GAMES_FAIL";
export const LOAD_DEFAULT_GAMES_SUCCESS = "LOAD_DEFAULT_GAMES_SUCCESS";
export const LOAD_DEFAULT_GAMES_FAIL = "LOAD_DEFAULT_GAMES_FAIL";
export const LOAD_FAVORITE_GAMES_SUCCESS = "LOAD_FAVORITE_GAMES_SUCCESS";
export const LOAD_FAVORITE_GAMES_FAIL = "LOAD_FAVORITE_GAMES_FAIL";
export const SCHEDULE_CLEAR = "SCHEDULE_CLEAR";

//Individual game actions
export const LOAD_GAME_SUCCESS = "LOAD_GAME_SUCCESS";
export const LOAD_GAME_FAIL = "LOAD_GAME_FAIL";
export const SET_CUSTOM_SCORE = "SET_CUSTOM_SCORE";
export const CONNECT_SOCKET_SUCCESS = "CONNECT_SOCKET_SUCCESS";
export const CONNECT_SOCKET_FAIL = "CONNECT_SOCKET_FAIL";
export const ACTIVATE_GAME_SUCCESS = "ACTIVATE_GAME_SUCCESS";
export const ACTIVATE_GAME_FAIL = "ACTIVATE_GAME_FAIL";
export const SCORE_GAME_SUCCESS = "SCORE_GAME_SUCCESS";
export const SCORE_GAME_FAIL = "SCORE_GAME_FAIL";
export const VIEW_EDIT_SCOREBOARD = "VIEW_EDIT_SCOREBOARD";
export const NOVIEW_EDIT_SCOREBOARD = "NOVIEW_EDIT_SCOREBOARD";
export const MESSAGE_GAME_SUCCESS = "MESSAGE_GAME_SUCCESS";
export const MESSAGE_GAME_FAIL = "MESSAGE_GAME_FAIL";
export const COMPLETE_GAME_SUCCESS = "COMPLETE_GAME_SUCCESS";
export const COMPLETE_GAME_FAIL = "COMPLETE_GAME_FAIL";
export const CLEAR_GAME = "CLEAR_GAME";
